var song_list = {
    "001": {
        title: "Spaceship",
        bpm: "120",
        tags: "#ambient #dark",
        duration: "02:49",
        track: "1Spaceship.mp3",
    },
    "002": {
        title: "McFli",
        bpm: "154",
        tags: "#Trap #hard",
        duration: "03:20",
        track: "2mcfli.mp3",
    },
    "003": {
        title: "New World",
        bpm: "150",
        tags: "#Metro Boomin #Future",
        duration: "03:26",
        track: "3New_World.mp3",
    },
    "004": {
        title: "Last Night Long",
        bpm: "138",
        tags: "#dark #Trap",
        duration: "03:54",
        track: "4Last_Night_Long.mp3",
    },
    "005": {
      title: "wish you tell me",
      bpm: "160",
      tags: "#guitar #killy",
      duration: "03:12",
      track: "5Wish_you_tell_me.mp3",
    },
    "006": {
        title: "Better Days ahead",
        bpm: "140",
        tags: "#lil peep #gbc",
        duration: "03:29",
        track: "6Better_Days_ahead.mp3",
    },
    "007": {
        title: "You Hang Up And I",
        bpm: "91",
        tags: "liluzivert #PlayboiCARTI",
        duration: "03:59",
        track: "7You_Hang_Up_And_I.mp3",
    },
    "008": {
        title: "civic",
        bpm: "160",
        tags: "lil tecca #lil Mosey",
        duration: "03:13",
        track: "8civic.mp3",
    },
    "009": {
        title: "Apocalyspe",
        bpm: "90",
        tags: "#Young lean #lil peep",
        duration: "04:02",
        track: "9Apocalypse.mp3",
    },
    "010": {
        title: "where is my lighter",
        bpm: "95",
        tags: "#piano #intense",
        duration: "03:52",
        track: "10Where_is_my_lighter.mp3",
    },
}
